---

- hosts: all
  gather_facts: yes
  tasks:
  - name: ping em todas as máquinas
    ping:

  - name: Ensure git is installed (Debian).
    apt:
      name: git      
      state: installed
      # shell: apt-get install git -y 

  - name: Setup do Docker
    shell: curl -sSL https://get.docker.io | sh


  - name: Install Docker Compose
    get_url:
      url: 'https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64'
      dest: '/usr/local/bin/docker-compose'
      force: True
      owner: 'root'
      group: 'root'
      mode: '0755'

