---
- name: add docker repository key
  sudo: yes
  shell: curl https://get.docker.io/gpg | apt-key add -

- name: add docker repository
  sudo: yes
  shell: echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list

- name: update apt
  apt: update_cache=yes
  sudo: yes

- name: install docker
  apt: pkg=lxc-docker state=installed
  sudo: yes

- name: install docker-compose
  when: docker_compose_binary.stdout == ""
  shell: >
    curl -LsS https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ kernel_arch.stdout}} > /tmp/docker-compose
    && mv /tmp/docker-compose {{ docker_compose_prefix }}/docker-compose
    && chmod 755 {{ docker_compose_prefix}}/docker-compose

